//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpinTheImage.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpinTheImage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   選択されたフォルダの名称が不正です。
        ///再度、画像データが存在するフォルダを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CombineImagesDirectoryErrorIncorrectPath {
            get {
                return ResourceManager.GetString("CombineImagesDirectoryErrorIncorrectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択されたフォルダにアクセスできませんでした。
        ///再度、画像データが存在するフォルダを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CombineImagesDirectoryErrorNotAccess {
            get {
                return ResourceManager.GetString("CombineImagesDirectoryErrorNotAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択されたフォルダに画像データが存在しません。
        ///画像データが存在するフォルダを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CombineImagesDirectoryErrorNotImage {
            get {
                return ResourceManager.GetString("CombineImagesDirectoryErrorNotImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像データを格納しているフォルダが選択されていません。
        ///画像データが格納されているフォルダを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CombineImagesDirectoryNotSelect {
            get {
                return ResourceManager.GetString("CombineImagesDirectoryNotSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像データを格納しているフォルダを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CombineImagesDirectorySelectDialogTitle {
            get {
                return ResourceManager.GetString("CombineImagesDirectorySelectDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択されたGifファイルが存在しません。削除または移動された可能性があります。
        ///再度選択するか、クリアをしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CombineImagesGifFileErrorNoGif {
            get {
                return ResourceManager.GetString("CombineImagesGifFileErrorNoGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gifファイルを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CombineImagesGifFileErrorNotGif {
            get {
                return ResourceManager.GetString("CombineImagesGifFileErrorNotGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gifファイル(*.GIF;*.gif)|*.GIF;*.gif|すべてのファイル(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CombineImagesGifFileSelectDialogFilter {
            get {
                return ResourceManager.GetString("CombineImagesGifFileSelectDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   追記の元となるGifファイルを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CombineImagesGifFileSelectDialogTitle {
            get {
                return ResourceManager.GetString("CombineImagesGifFileSelectDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gifを作成する過程で生成したPngファイルを保存するディレクトリ名の生成に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateGifErrorNotGenerateDirectoryName {
            get {
                return ResourceManager.GetString("CreateGifErrorNotGenerateDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap DragDrop_Black {
            get {
                object obj = ResourceManager.GetObject("DragDrop_Black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap DragDrop_White {
            get {
                object obj = ResourceManager.GetObject("DragDrop_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Enable_False {
            get {
                object obj = ResourceManager.GetObject("Enable_False", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   全ての設定をリセットしますがよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemRestoreDefaultSettingsMessage {
            get {
                return ResourceManager.GetString("MenuItemRestoreDefaultSettingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像ファイルをドラッグ＆ドロップしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PictureBoxPreviewNoDataErrorMessage {
            get {
                return ResourceManager.GetString("PictureBoxPreviewNoDataErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データが読み込みできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RoteteParameterFileErrorIOException {
            get {
                return ResourceManager.GetString("RoteteParameterFileErrorIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RoteteParameterFileErrorNoData {
            get {
                return ResourceManager.GetString("RoteteParameterFileErrorNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   下記の行番号のデータが数値に変換できませんでした。{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RoteteParameterFileErrorNotFloat {
            get {
                return ResourceManager.GetString("RoteteParameterFileErrorNotFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///{0}行目 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RoteteParameterFileErrorNotFloatLineNum {
            get {
                return ResourceManager.GetString("RoteteParameterFileErrorNotFloatLineNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テキストファイル(*.TXT;*.txt)|*.TXT;*.txt|すべてのファイル(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RoteteParameterFileSelectDialogFilter {
            get {
                return ResourceManager.GetString("RoteteParameterFileSelectDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回転パラメータに使用するテキストファイルを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RoteteParameterFileSelectDialogTitle {
            get {
                return ResourceManager.GetString("RoteteParameterFileSelectDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理が終了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RunProcessEndMessage {
            get {
                return ResourceManager.GetString("RunProcessEndMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回転させる画像が設定されていません。画像ファイルをドラッグ＆ドロップしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RunProcessErrorNoRoteteImage {
            get {
                return ResourceManager.GetString("RunProcessErrorNoRoteteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理を中断しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RunProcessStopMessage {
            get {
                return ResourceManager.GetString("RunProcessStopMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gifファイル(*.GIF;*.gif)|*.GIF;*.gif|すべてのファイル(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RunSaveFileDialogFilter {
            get {
                return ResourceManager.GetString("RunSaveFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存先を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RunSaveFileDialogTitle {
            get {
                return ResourceManager.GetString("RunSaveFileDialogTitle", resourceCulture);
            }
        }
    }
}
